#!/command/with-contenv bash

PUID=${PUID:-9999}
PGID=${PGID:-9999}
VOLT_HOME=${VOLT_HOME:-"/var/www/html"}

if [[ $PUID != 9999 || $PGID != 9999 ]]; then

    # Change the group ID
    groupmod -o -g "$PGID" voltgroup

    # Change the User ID
    usermod -o -u "$PUID" volt

    # Make sure the home directory is updated with the proper UID & GID
    chown volt:voltgroup $VOLT_HOME
fi

echo '
--------------------------------------------------------------------
              ____
 _   ______  / / /_
| | / / __ \/ / __/
| |/ / /_/ / / /_
|___/\____/_/\__/

Brought to you by voltauto.io
--------------------------------------------------------------------'

echo '
-------------------------------------
GID/UID
-------------------------------------'
echo "
User uid:    $(id -u volt)
User gid:    $(id -g volt)
-------------------------------------
"
