name: Test

on: [ pull_request ]

jobs:
  build-test:
    name: PHP ${{ matrix.php }}
    runs-on: ubuntu-latest

    env:
      DB_DATABASE: volt
      DB_USERNAME: volt
      DB_PASSWORD: volt

    strategy:
      fail-fast: false
      matrix:
        php: [ '8.1' ]

    services:
      db:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: volt
          MYSQL_DATABASE: volt
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Copy .env
        run: |
          php -r "file_exists('.env') || copy('.env.testing.example', '.env');"
      - name: Install dependencies
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: exif, mbstring, dom, fileinfo, mysql, common
          coverage: xdebug

      - name: Install PHP dependencies
        run: composer install --ignore-platform-reqs --no-interaction --no-progress
        if: 'matrix.php >= 8'

      - name: Generate Application key
        run: php artisan key:generate --show --env=testing

      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Run Migration
        run: php artisan db:seed
        env:
          DB_DATABASE: volt
          DB_USERNAME: volt
          DB_PASSWORD: volt
          DB_HOST: db
          DB_PORT: ${{ job.services.db.ports['3306'] }}

      - name: Test with phpunit
        run: vendor/bin/phpunit --testdox
        env:
          DB_PORT: ${{ job.services.db.ports['3306'] }}
