name: Test

on: [ pull_request ]

jobs:
  build-test:
    name: PHP ${{ matrix.php }}
    runs-on: ubuntu-latest

    env:
      DB_DATABASE: volt
      DB_USERNAME: root
      DB_PASSWORD: volt

    strategy:
      fail-fast: false
      matrix:
        php: [ '8.1' ]

    services:
      db:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: volt
          MYSQL_DATABASE: volt
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Copy .env
        run: |
          php -r "file_exists('.env') || copy('.env.testing.example', '.env');"

      - name: Setup PHP extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: exif, mbstring, dom, fileinfo, mysql
          coverage: xdebug

      - name: Install PHP dependencies
        run: composer install --ignore-platform-reqs --no-interaction --no-progress

      - name: Generate Application key
        run: php artisan key:generate

      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Run Migration
        run: php artisan migrate:fresh

      - name: Run Seeders
        run: php artisan db:seed

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 18

      - name: Install Node dependencies
        uses: bahmutov/npm-install@v1

      - name: Build Assets with Vite Before Tests
        run: npm run build

      - name: Test with pest
        run: vendor/bin/pest
